# openapi2-run.yaml
swagger: "2.0"
info:
  title: sterndeck-4
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://completion-i5rcwtaovq-uc.a.run.app
paths:
  /:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            # Body schema with atomic property examples
            type: object
            properties:
              model:
                type: string
              prompt:
                type: string
      operationId: getAsset
      responses:
        200:
          description: "200 response"
          examples:
            application/json: { "status": "Success" }
