swagger: "2.0"
info:
  title: sterndeck-4
  version: "1.0.0"
host: api-dev.sterndeck.com
schemes:
  - https
paths:
  /:
    post:
      summary: "completion"
      operationId: modelCompletion
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              model:
                type: string
              prompt:
                type: string
      responses:
        200:
          description: "completion"
      x-google-backend:
        address: "https://completion-i5rcwtaovq-uc.a.run.app"
        disable_auth: true
