swagger: "2.0"
info:
  title: sterndeck-4
  version: "1.0.0"
host: api-dev.sterndeck.com
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
security:
  - firebase: []
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/sterndeck-4"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "sterndeck-4"
paths:
  /api/v1/user-key:
    post:
      summary: "user-key"
      operationId: user-key
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_uid:
                type: string
              secret:
                type: string
      responses:
        200:
          description: "user-key"
      x-google-backend:
        address: "https://http-user-secret-create-i5rcwtaovq-uc.a.run.app"
  /api/v1/fine-tunes-create:
    post:
      summary: "fine-tunes-create"
      operationId: fine-tunes-createl
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_uid:
                type: string
              training_file_id:
                type: string
              path:
                type: string
      responses:
        200:
          description: "fine-tunes-create"
      x-google-backend:
        address: "https://http-fine-tunes-create-i5rcwtaovq-uc.a.run.app"
  /api/v1/fine-tunes-cancel:
    post:
      summary: "fine-tunes-cancel"
      operationId: fine-tunes-cancel
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_uid:
                type: string
              fine_tune_id:
                type: string
              path:
                type: string
      responses:
        200:
          description: "fine-tunes-cancel"
      x-google-backend:
        address: "https://http-fine-tunes-cancel-i5rcwtaovq-uc.a.run.app"
  /api/v1/upload:
    post:
      summary: "upload"
      operationId: upload
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upload
          type: string
          required: true
        - in: formData
          name: model_id
          type: string
          required: true
        - in: formData
          name: user_uid
          type: string
          required: true
        - in: formData
          name: file_id
          type: string
          required: true
      responses:
        200:
          description: "upload"
      x-google-backend:
        address: "https://http-csv-upload-i5rcwtaovq-uc.a.run.app"
