openapi: 3.0.0
info:
  title: sterndeck-4
  description: A simple API to manage a list of tasks
  version: 1.0.0
servers:
  - url: https://dev-api.sterndeck.com
x-google-endpoints:
  - name: api-dev.sterndeck.com
    allowCors: true
paths:
  /api/v1/feedback:
    post:
      summary: feedback
      operationId: feedback
      security:
        - speakeasy_api_key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: string
                prompt:
                  type: string
                completion:
                  type: string
        required: true
      responses:
        "200":
          description: feedback
      x-google-backend:
        address: https://http-models-feedback-i5rcwtaovq-uc.a.run.app
components:
  securitySchemes:
    speakeasy_api_key:
      type: oauth2
      x-google-issuer: https://app.speakeasyapi.dev/v1/auth/oauth/clftpkq5b00003b6cfhekkcbu
      x-google-jwks_uri: https://app.speakeasyapi.dev/v1/auth/oauth/clftpkq5b00003b6cfhekkcbu/.well-known/jwks.json
      x-google-audiences: sterndeck
      flows:
        implicit:
          authorizationUrl: /
          scopes: {}
